question_data = [
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The planet Mars has two moons orbiting it.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In what year was the game &quot;Fallout&quot; released?",
        "correct_answer": "1997",
        "incorrect_answers": ["1998", "1999", "1996"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "easy",
        "question": "Who won the 2016 Formula 1 World Driver&#039;s Championship?",
        "correct_answer": "Nico Rosberg",
        "incorrect_answers": ["Lewis Hamilton", "Max Verstappen", "Kimi Raikkonen"],
    },
    {
        "category": "History",
        "type": "multiple",
        "difficulty": "easy",
        "question": "How was Socrates executed?",
        "correct_answer": "Poison",
        "incorrect_answers": ["Decapitation", "Firing squad", "Crucifixion "],
    },
    {
        "category": "Entertainment: Board Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "&quot;Rich Uncle Pennybags&quot; from the board game &quot;Monopoly&quot; wears a monocle.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Sports",
        "type": "multiple",
        "difficulty": "hard",
        "question": "Who is Manchester United&#039;s leading appearance maker?",
        "correct_answer": "Ryan Giggs",
        "incorrect_answers": ["David Beckham", "Wayne Rooney", "Eric Cantona"],
    },
    {
        "category": "Science & Nature",
        "type": "multiple",
        "difficulty": "hard",
        "question": "Which of the following are cells of the adaptive immune system?",
        "correct_answer": "Cytotoxic T cells",
        "incorrect_answers": [
            "Dendritic cells",
            "Natural killer cells",
            "White blood cells",
        ],
    },
    {
        "category": "Entertainment: Music",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which one of these people has been in the band &#039;&#039;Metallica&#039;&#039; in the past?",
        "correct_answer": "Dave Mustaine",
        "incorrect_answers": ["Kurt Cobain", "Joey Belladonna", "Dave Lombardo"],
    },
    {
        "category": "Science: Mathematics",
        "type": "multiple",
        "difficulty": "medium",
        "question": "In the complex plane, multiplying a given function by i rotates it anti-clockwise by how many degrees?",
        "correct_answer": "90",
        "incorrect_answers": ["180", "270", "0"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    }
]
